### ISSUE TITLE
Mobile Version App

### ISSUE THREAD

**Issue by mirwaisfarahi** [Solo7991/Module1Block1Portfolio#4]
**Suggestions:**

1. It will be good practice to use type attribute for buttons in your HTML file.
2. It is good to have descriptive alt attribute for your img tag according to what image represents.
3. I recommend to use img tag for work section images instead of putting them inside css file as a background image.
4. The skills and technologies section can be written as follows:
<ul>
    <li>Languages
        <ul>
            <li>Html</li>
            <li>CSS</li>
           <li>Javascript</li>
        </ul>
    </li>
    <li>Frameworks</li>
    <li>skills</li>
</ul>

**Comment by Solo7991** [comment]
I'll make changes based on these recommendations.

**Comment by Solo7991** [comment]
Post newer issues just below
